### ISSUE TITLE
Game Crash when pick potion

### ISSUE THREAD

**Issue by auusi9** [joeyGumer/Pixel_Mirror--Diablo_II#13]
**Frequency:** 100%;
**Descriptionof the bug:**  When player picks a potion from a killed enemy game crash.
**Steps to reproduce:** 
1- Kill a enemy
2- If potion falls from the enemy, pick that potion
3- Game Crash
**Additional information:** 
Game crashes on this line : "if (objective->type == PORTAL)"

**Comment by joeyGumer** [comment]
This issue was not fixed: 

The conditions to make it appear were clicking to many time when getting an item, an that the input_locked stayed true.

**Comment by joeyGumer** [comment]
Issue solved:

The problem was the input_locked variable, is uselless, it only gave problems like this.
