### ISSUE TITLE
When defeating boss not loading main menu

### ISSUE THREAD

**Issue by auusi9** [joeyGumer/Pixel_Mirror--Diablo_II#14]
**Frequency:** 100% ;
**Description of the bug:** When you defeat the boss and then you kill a normal enemy, main menu dosent't load. 
**Steps to reproduce:** 
1- Kill the boss.
2- Kill a normal enemy before main menu loads
3- Then the screen keeps black all the time

**Comment by joeyGumer** [comment]
I'm testing this and the error doesn't appear
