### ISSUE TITLE
Some units won't attack the player

### ISSUE THREAD

**Issue by Vulpem** [joeyGumer/Pixel_Mirror--Diablo_II#21]
Priority low
Gameplay

Some apparently random enemies won't attack the player when he gets close.

![captura](https://cloud.githubusercontent.com/assets/10261951/15072281/b19c44d4-1389-11e6-8f7d-36c53c85e277.PNG)

**Comment by ianexe** [comment]
Issue solved, caused by not initializing "attacking" bool on Enemy Entities
